apiVersion: v1
kind: ReplicationController
metadata:
   name: myjavaapp-rc
spec:
  replicas: 3
  selector:
    app:  myjavaapp-pod
  template:
    metadata:
     labels: 
      app: myjavaapp-pod
    spec:
     containers:
     - name: myjavaapp-container
       image: jenkins:1
       ports:
       - containerPort: 8080